# Makefile for local
#

db-deps:
	mkdir db
	cd db && git clone https://github.com/bibi21000/janitoo_mysql
	cd db && git clone https://github.com/bibi21000/janitoo_mysql_client
	cd db && git clone https://github.com/bibi21000/janitoo_postgresql
	cd db && git clone https://github.com/bibi21000/janitoo_postgresql_client
	sudo mysql --host=localhost --user=root -e "CREATE DATABASE IF NOT EXISTS janitoo_db_full_tests;"
	sudo -u postgres createdb janitoo_db_full_tests
	mkdir tmp
	cd tmp && git clone https://github.com/bibi21000/janitoo_layouts
	cd tmp && git clone https://github.com/bibi21000/janitoo_dhcp
	cd tmp && git clone https://github.com/bibi21000/janitoo_manager
	ln -s tmp/janitoo_db/tests tests/janitoo_db
	ln -s tmp/../janitoo_layouts/tests tests/janitoo_layouts
	ln -s tmp/../janitoo_dhcp/tests tests/janitoo_dhcp
	ln -s tmp/../janitoo_manager/tests tests/janitoo_manager
